### ISSUE TITLE
LocalizationStringKey display in widget

### ISSUE THREAD

**Issue by Dewerro** [asiliuk/BsuirScheduleApp#130]
Without localized string there is a key.

1. Create widget on lock screen
2. Select group 263102

![IMG_3296](https://user-images.githubusercontent.com/79833946/211158554-86b3e84f-4d68-46fd-9e45-b735de9e8a92.jpeg)

 - Device: iPhone XR
 - OS: 16.1
 - App Version: 2.9.1(58)

**Comment by asiliuk** [comment]
Will be fixed in 3.0
