### ISSUE TITLE
https://iis.bsuir.by/api/v1/schedule?studentGroup=224403 keyNotFound(CodingKeys(stringValue: "schedules", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: "schedules", intValue: nil) ("schedules").", underlyingError: nil))

### ISSUE THREAD

**Issue by ulyanaaaaaa** [asiliuk/BsuirScheduleApp#164]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment information (please complete the following information):**
 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS13.1]
 - App Version [e.g. 1.0.0(123)]

**Additional context**

**Comment by asiliuk** [comment]
Will be fixed in v3.3
