### ISSUE TITLE
API problem

### ISSUE THREAD

**Issue by ulyanaaaaaa** [asiliuk/BsuirScheduleApp#166]
https://iis.bsuir.by/api/v1/schedule?studentGroup=224403
keyNotFound(CodingKeys(stringValue: "schedules", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: "schedules", intValue: nil) ("schedules").", underlyingError: nil))
 - Device: iPhone12
 - OS: iOS17.2.1
 - App Version 3.2.1(99)

**Comment by asiliuk** [comment]
Will be fixed in v3.3
