### ISSUE TITLE
Отсутствие отклика на расписание

### ISSUE THREAD

**Issue by fferikvalik** [asiliuk/BsuirScheduleApp#172]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment information (please complete the following information):**
 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS13.1]
 - App Version [e.g. 1.0.0(123)]

**Additional context**

**Comment by asiliuk** [comment]
Нужно больше информации, пожалуйста
