### ISSUE TITLE
Yesterday pairs are shown like they are all not for my subgroup

### ISSUE THREAD

**Issue by Archichil** [asiliuk/BsuirScheduleApp#173]
**Screenshots**
![image](https://github.com/asiliuk/BsuirScheduleApp/assets/114314218/5f25481c-86a9-4bd0-8a8c-7f6a1a9384af)

**Environment information:**
 - Device: [e.g. iPhone 14 Pro]
 - OS: [e.g. iOS 17.2.1]
 - App Version [e.g. 3.3.2(107)]

**Comment by asiliuk** [comment]
да, так и задумано, чтобы меньше внимания привлекали неактуальные пары
это в основном для вкладки экзаменов сделано, но и на расписании так работает
