### ISSUE TITLE
Localizable name appears while trying to remove forcibly added group

### ISSUE THREAD

**Issue by Archichil** [asiliuk/BsuirScheduleApp#176]
**Screenshots**
![image](https://github.com/asiliuk/BsuirScheduleApp/assets/114314218/53ddfbfa-674d-415f-89cb-11bb8b9dda83)
![image](https://github.com/asiliuk/BsuirScheduleApp/assets/114314218/0c3df761-0e5a-49b6-aed5-c4b6cb125709)
![image](https://github.com/asiliuk/BsuirScheduleApp/assets/114314218/90507f78-0cf2-404c-9d53-acc9cf74f2c5)

**Environment information (please complete the following information):**
 - Device: iPhone 14 Pro 
 - OS: iOS 17.4
 - App Version 3.4.0(63)

**Comment by Archichil** [comment]
![image](https://github.com/asiliuk/BsuirScheduleApp/assets/114314218/2405130f-9648-42a0-bf64-3f037c9c5374)

**Comment by asiliuk** [comment]
Это не method name, это я забыл локализацию по ключу сделать
