### ISSUE TITLE
Лаги при скроллинге

### ISSUE THREAD

**Issue by WolfandWolf** [asiliuk/BsuirScheduleApp#20]
- Device: iphone 6s
 - OS: 14.1
 - App Version: последняя

Тормозит скроллинг расписания, как будто подгрузка не асинхронная

**Comment by asiliuk** [comment]
@WolfandWolf проверь пожалуйста новую версию в сторе, 2.2.1 должно стать чуть лучше
если будет все еще плохо, дай знать, буду сильнее копать

**Comment by WolfandWolf** [comment]
Чекнул, трохи хуже стало

вт, 17 нояб. 2020 г. в 13:34, Anton Siliuk <notifications@github.com>:

**Comment by asiliuk** [comment]
@WolfandWolf плохо) ладно, буду переписывать все

**Comment by asiliuk** [comment]
@WolfandWolf как скролл в новом апдейте? Должно быть ок

**Comment by WolfandWolf** [comment]
Чекнул, стало нормально. Если сильно быстро начинать скролл, то лаги небольшие есть, но я думаю уже не критично
