### ISSUE TITLE
Как обновить расписание?

### ISSUE THREAD

**Issue by nevack** [asiliuk/BsuirScheduleApp#21]
Новый семестр начался, а расписание от прежнего. В другой аппе обновил и появилось новое, в твоем приложении не нашел как это сделать.

**Comment by asiliuk** [comment]
@nevack там на экране "о приложении" есть кнопка очистить кэш. Попробуй ее и рестартануть приложение.
Более адекватный способ сделаю попозже

**Comment by nevack** [comment]
Я пробовал, не помогло 😔
