### ISSUE TITLE
iOS 15 support

### ISSUE THREAD

**Issue by anton-patrushev** [asiliuk/BsuirScheduleApp#28]
**Description**
App crashes on iOS 15 immediately after launching.

**Steps to reproduce**
1. Open app.

**Expected behavior**
App launched successfully and works correctly (Main Schedule page should be opened).

**Actual behavior**
App launched and after about 1 sec crashes.

**Environment information (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 15.0
 - App Version: 2.3.2

**Comment by asiliuk** [comment]
Will be fixed in 2.4.0
