### ISSUE TITLE
Schedule fails to load for some groups

### ISSUE THREAD

**Issue by asiliuk** [asiliuk/BsuirScheduleApp#94]
At leas of ..605 group it is the issue with empty weekNumber for pair model. They have some special one-time pair that has date and is not repeating that's why theres no week number for it

This should be fixed same way as exams schedule, because same method is used to represent exam on a specific date

Groups:
- 961401
- 961402
- 020605
- 110201

**Comment by Dewerro** [comment]
Error cause on application side. `weekDay` in API has int value, not null.

Error log:
Days: received Failure. decodeError(Swift.DecodingError.valueNotFound(Swift.Int, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "schedules", intValue: nil), WeekDay(stringValue: "Вторник", intValue: nil), _JSONKey(stringValue: "Index 1", intValue: 1), CodingKeys(stringValue: "weekNumber", intValue: nil)], debugDescription: "Expected Int but found null value instead.", underlyingError: nil)))

**Comment by asiliuk** [comment]
> CodingKeys(stringValue: "weekNumber", intValue: nil)], debugDescription: "Expected Int but found null value instead.", underlyingError: nil)))

Not sure where you got weekDay value issue. In error message it says “‘weekNumber’, Expected Int but found null value instead”
So it tries to parse it, but there’s no value. In case when pair is not repeatable and has specific date

**Comment by asiliuk** [comment]
Groups 
* 961401
* 961402
* 020605

Had a new announcement thing among pairs that didn't have weekNumber. Will be fixed in next commit
Don't know what happened to `110201`, now it is working, maybe it had announcement, but it passed
